# Generated by Django 3.2 on 2021-04-08 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=15, null=True)),
                ('company_contact', models.CharField(max_length=30, null=True)),
                ('company_location', models.CharField(max_length=15, null=True)),
                ('company_email', models.CharField(max_length=15, null=True)),
                ('company_type', models.CharField(max_length=15, null=True)),
                ('company_details', models.CharField(max_length=1000, null=True)),
                ('recruiter_name', models.CharField(max_length=15, null=True)),
                ('recruiter_contact', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('education', models.CharField(max_length=50, null=True)),
                ('interested_in', models.CharField(max_length=50, null=True)),
                ('cvImages', models.FileField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
