# Generated by Django 3.2 on 2021-04-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cvImages',
            new_name='cv',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='interestedIN',
            new_name='interested_in',
        ),
    ]
