# Generated by Django 3.2 on 2021-04-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210408_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cv',
        ),
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seeker/'),
        ),
    ]
